vim.opt.colorcolumn = "120"
vim.opt.undodir = vim.fn.stdpath('data') .. '/undo'
vim.opt.undofile = true
vim.opt.tabstop = 2
vim.opt.softtabstop = -1
vim.opt.shiftwidth = 0
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.number = true
